### ISSUE TITLE
Ni line in 6767 (the helioseismology GONG/MDI line)

### ISSUE THREAD

**Issue by vmpillet** [barklem/abo-cross#1]
Hi

I get the message below when I try to compute the broadening coefficients for the Ni line in 6767 that is used in GONG/MDI for helioseismology and magnetic field measurements.

_!!! Outside range of tables! (p-d)
Unable to get xsection for line at  6767.772A
             for above reason.
n* are   1.53 ->   1.85
  
 Output written to file!_

Input line is 

**$$$ Ni I GONG line
Ni 1    6767.772        14728.840       61619.77        29500.674      61619.77          2  1  0    1**

Any help is much appreciated.

Valentin

**Comment by barklem** [comment]
Hi Valentin

This just means the lines lie outside the bounds of the tabulated data where interpolation can be done.  I'll look next week what can be done - perhaps a special calculation.  There is usually a way to get an estimate at least.

Paul

**Comment by barklem** [comment]
Hi Valentin

In this case the lower state has n* = 1.53, and this is too low for the use of Coulomb wavefunctions for d states (n*-l must be >0 for hydrogenic Coulomb wavefunctions to be defined).  There are two possible approaches here which don't involve me writing new code, and probably give good  estimates (i.e. similar uncertainties to any other line calculated with ABO theory):  

1) Ignore the lower state.  A specific calculation gives sigma = 322, alpha = 0.286.
2) Include an estimate of the effect of the lower state by regarding it as an s-state.  You could do this by just switching "l=2" to "l=0" for the lower state in your input.  I did a specific calculation (i.e. I didn't use abo-cross, and thus there is no interpolation involved) and get sigma = 301, alpha = 0.244.

My expectation is that 2 would be better than 1, since it gives an estimate of the interference between the two states (that's why there is a slight decrease).  But 1 gives you an idea of the uncertainty.

Cheers, Paul
